add encryptor
paromad/python pull request #1
Opened 2020-04-15 16:58 UTC by paromad

2020-04-17 13:36 UTC, WokinShopash requested changes

2020-04-17 13:36 UTC, WokinShopash commented on encryptor.py
> +if args.act == "train":
train не работает, когда файл задается через --text-file

2020-04-23 10:35 UTC, tardis-forever requested changes

2020-04-23 10:35 UTC, tardis-forever commented on encryptor.py
> +if args.act == "train":
train не работает на файлах, в которых есть не только lowercase буквы. Сдаваемый на review код должен корректно работать на _всех_ корретных выходных данных.

В результате исправлений по этому комментарию ожидается уже _полноценно_ работающий на всех корректных сценариях код.

2020-04-23 15:36 UTC, tardis-forever commented
Реквест в состоянии draft, но запрос на ревью стоит. Еще рано смотреть, или нет?

2020-04-23 19:38 UTC, tardis-forever commented
Напиши в ветку обсуждений тогда комментарий, когда закончишь с правками

2020-04-23 20:16 UTC, paromad commented
Я вроде как закончила, можно смотреть)

2020-04-24 11:12 UTC, paromad commented
Можно смотреть

2020-04-24 12:34 UTC, tardis-forever requested changes

2020-04-24 12:34 UTC, tardis-forever commented on encryptor.py
> +        return lowercase[(lowercase.index(i) + key) % 26]
Магическая константа в коде

2020-04-24 12:34 UTC, tardis-forever commented on encryptor.py
> +        res += encryption_caesar_symbol(i, key)
Не надо конкатенировать строки в цикле, они иммутабельные и каждый раз копируются

2020-04-24 12:34 UTC, tardis-forever commented on encryptor.py
> +        return uppercase[(uppercase.index(i) + lowercase.index(key[num % len(key)].lower())) % 26]
Строка выглядит практически как в предыдушей условной ветке
Стоит выделить общие элементы отдельно, чтобы избежать дублирований кода

2020-04-24 12:34 UTC, tardis-forever commented on encryptor.py
> +        res += encryption_vigenere_symbol(s[i], count, key)
Конкатенация строк

2020-04-24 12:34 UTC, tardis-forever commented on encryptor.py
> +        return uppercase[(uppercase.index(i) + 26 - key % 26) % 26]
Константа

2020-04-24 12:34 UTC, tardis-forever commented on encryptor.py
> +        res += decryption_caesar_symbol(i, key)
Конкатенация

2020-04-24 12:34 UTC, tardis-forever commented on encryptor.py
> +            (uppercase.index(i) + 26 - lowercase.index(key[num % len(key)].lower())) % 26
Константа, дублирование кода

2020-04-24 12:34 UTC, tardis-forever commented on encryptor.py
> +def decryption_caesar(s, key):
Сами функции `decrypt` сильно дублируют соответствующие `encrypt`

2020-04-24 12:34 UTC, tardis-forever commented on encryptor.py
> +    arr = {}
1. Странно называть `dict` именем `arr`. 
2. Нужно давать говорящие названия переменным.

2020-04-24 12:34 UTC, tardis-forever commented on encryptor.py
> +        arr[i] = 0
Для этого есть `defaultdict`

2020-04-24 12:34 UTC, tardis-forever commented on encryptor.py
> +    for i in range(26):
Константа

2020-04-24 12:34 UTC, tardis-forever commented on encryptor.py
> +def compare_chart(dict, arr):
`dict` - один из типов в python. Не надо так называть переменные

2020-04-24 12:34 UTC, tardis-forever commented on encryptor.py
> +def process_decode(args):
Дублирование кода с `process_encode`

2020-04-24 12:34 UTC, tardis-forever commented on encryptor.py
> +    main()
Нет пустой строки в конце файла

2020-05-04 16:34 UTC, tardis-forever requested changes

2020-05-04 16:34 UTC, tardis-forever commented on encryptor.py
> +cycle = 26
Магическая константа

2020-05-04 16:34 UTC, tardis-forever commented on encryptor.py
> +    for i in range(len(s)):
Если индекс не нужен, можно итерироваться сразу по значениям из контейнера

2020-05-04 16:34 UTC, tardis-forever commented on encryptor.py
> +        dict_s = bar_chart(res)
Можно на каждом шаге не пересчитывать заново гистограмму, а вычислять новое значение неа основе предыдущего

2020-05-04 16:34 UTC, tardis-forever commented on encryptor.py
> +                f.write(res[i])
Можно записать сразу все, а не по одному символу

2020-05-04 16:34 UTC, tardis-forever commented on encryptor.py
> +            print(res[i], end="")
Здесь то же самое. И про итерацию по контейнеру тоже.

2020-05-04 16:34 UTC, tardis-forever commented on encryptor.py
> +            key = 26 - key % 26
Магическая константа

2020-05-04 16:34 UTC, tardis-forever commented on encryptor.py
> +                new_key.append(lowercase[(26 - lowercase.index(i) % 26) % 26])
И снова

2020-05-04 16:34 UTC, tardis-forever commented on encryptor.py
> +        s = sys.stdin.read()
Дублирование кода ввода-вывода

2020-05-09 10:45 UTC, tardis-forever requested changes

2020-05-09 10:45 UTC, tardis-forever commented on encryptor.py
> +        return caesar_symbol(i, key, lowercase if i in lowercase else uppercase)
Возможно, здесь лучше вместо проверки через `in` использовать `islower()`

2020-05-09 10:45 UTC, tardis-forever commented on encryptor.py
> +    return "".join(encryption_caesar_symbol(i, key) for i in s)
Лучше не использовать `i` при итерации по символам, а не по численным данным

2020-05-09 10:45 UTC, tardis-forever commented on encryptor.py
> +    for i in s.lower():
Здесь создается целая строка длины как исходный текст - возможно, стоит лучше каждый отдельный символ преобразовывать в нижний регистр

2020-05-09 10:45 UTC, tardis-forever commented on encryptor.py
> +def next_bar_chart(dict_s):
Можно не создавать явно новый словарь на каждой итерации, а просто вычислять нужные частоты "на лету"

2020-05-12 09:12 UTC, tardis-forever requested changes

2020-05-12 09:12 UTC, tardis-forever commented on encryptor.py
> +    return "".join(char for char in res)
Здесь можно просто `"".join(res)`

2020-05-12 09:12 UTC, tardis-forever commented on encryptor.py
> +def write_text(args, res):
Почему здесь передаются все `args`, а в `get_text` - только имя файла?

2020-05-15 11:06 UTC, tardis-forever commented
ок

2020-05-15 11:06 UTC, merged